source 'https://rubygems.org'


gem 'rails', '4.2.4'

gem 'rails-api'

gem 'spring', :group => :development


gem 'pg'


# To use Jbuilder templates for JSON
gem 'jbuilder'

gem 'sunspot_rails'
gem 'sunspot_solr'

gem 'foreman'

group :test do
  gem 'factory_girl_rails', '~> 4.0'
  gem 'rspec-rails'
  gem 'hashie'
  gem 'sunspot_test'
end

group :production do
  gem 'rails_12factor'
end